### ISSUE TITLE
in createAccount.cpp dosent return anything

### ISSUE THREAD

**Issue by Lemorz56** [Aspect1337/HotelManagement_System#2]
https://github.com/Aspect1337/HotelManagement_System/blob/9453ce87dc5158d92731d1cd1e9ef23fd163081d/createAccount.cpp#L45-L60

Är tanken att det ska vara en Overload function eller bara missat typ?

**Comment by Lemorz56** [comment]
```
C:\Users\Sebastian\Desktop\GitHotel\HotelManagement_System\createAccount.cpp: In function 'user newAccount()':
C:\Users\Sebastian\Desktop\GitHotel\HotelManagement_System\createAccount.cpp:60:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
```

**Comment by Aspect1337** [comment]
Gjort om till en void funktion ( av någon anledning så funkade det för mig endå)
